name: Create release

on:
  push:
    branches: [release-script-fix]
  
jobs:
  build:
    name: "🚀 Release"
    runs-on: ubuntu-18.04
    steps:
      - name: "Check-out"
        uses: actions/checkout@v1
      - name: "Update Release CHANGELOG"
        id: update-release-changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          onlyLastTag: true
          stripHeaders: false
          base: "CHANGELOG.md"
          headerLabel: "# Changelog"
          breakingLabel: '### Breaking'
          enhancementLabel: '### Enhancements'
          stripGeneratorNotice: true
          bugsLabel: '### Fixes'
          issues: true
          issuesWoLabels: true
          pullRequests: true
          prWoLabels: true
          author: false
          verbose: true
 
