name: Mixpanel Swift SDK action

on:
  push:
    branches: [ master, 3.0.0.beta ]
  pull_request:
    branches: [ master, 3.0.0.beta ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['OS=14.4,name="iPhone 11"']

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        cd MixpanelDemo
        pod install --repo-update
    - name: Run Test
      working-directory: MixpanelDemo
      run: |
        set -o pipefail
        xcodebuild -workspace MixpanelDemo.xcworkspace -scheme MixpanelDemo -destination ${{ matrix.destination }} -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty -c;
    - name: Pod Lint
      run: pod lib lint --allow-warnings
